### ISSUE TITLE
Feature request: swagger docs

### ISSUE THREAD

**Issue by magick93** [SOM-Research/emf-rest#13]
Hello

It would be a nice feature if emf-rest also generated swagger documentation for the rest api.

**Comment by hamzaed** [comment]
Thank you for your comment. 

Indeed, we are studying the possibility of generating a Swagger definition as part of the generated application. Unfortunitaly, we didn't have much time recently to work on this project due to other prioritized tasks, but we are planning a new release of EMF-REST. Stay tuned!

Cheers,

Hamza
